config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # devise_for :admins
  resources :categories
  devise_for :admins
  root 'products#index'
  resources :products do 
  end
  resources :test_articles, path: '/test_articles', only: :index
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validate :email_cannot_have_bob

  def say_hello
    'Hello'
  end

  private

  def email_cannot_have_bob
    errors.add(:email, :cannot_have_bob) if email.include?('bob')
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

    has_many :comments
  
    validates :body, length: { minimum: 4 }
    validate :no_bad_words_in_title
  
    def no_bad_words_in_title
      if title.downcase.include?('bad')
        errors.add(:title, 'cannot contain bad words')
      end
    end
  end

app/models/category.rb
class Category < ApplicationRecord

    has_many :products
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/product.rb
class Product < ApplicationRecord

  validates :name, length: { minimum: 4 }
  validates :description, length: { minimum: 4 }
  validate :non_negative
  belongs_to :category
  
  def non_negative
    if stock.negative?()
      errors.add(:stock, 'cannot be negative')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @search = params[:search]

    @articles = Article.all
    @articles = @articles
      .where("title LIKE ? or body LIKE ?", "%#{@search}%", "%#{@search}%") if @search.present?
    @articles = @articles.page(params[:page]).per(5)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    puts "This is how you print out something."
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.create(article_params)

    if @article.invalid?
      flash[:error] = @article.errors.full_messages
    end

    redirect_to action: :index
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to action: :index
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to action: :index
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :desc)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find params[:article_id]
    @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :text)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def index
    end

    def about
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin!, only: [:create,:edit,:destroy]
  
  def index
    @search = params[:search]

    @products = Product.all
    @products = @products
      .where("title LIKE ? or body LIKE ?", "%#{@search}%", "%#{@search}%") if @search.present?
    @products = @products.page(params[:page]).per(5)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new 
    @product = Product.new 
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  def edit
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  def create
    @product = Product.new(product_params)
    @product.category_id = params[:category_id]
    if @product.invalid?
      # flash[:error] = @products.errors.objects.first.full_message
    end
    if @product.save
      flash[:success] = "Product created"
    end

    redirect_to action: :index
  end

  def update
    @product.category_id = params[:category_id]
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  
  def set_product
    @product = Product.find(params[:id])
  end
  def product_params
    params.require(:product).permit(:name, :description, :stock)
  end
end

app/controllers/test_articles_controller.rb
class TestArticlesController < ApplicationController
    before_action :authenticate_admin!, only: [:create,:edit,:destroy]
    # caches_page :index
    #rails dev:cache
    
    def index
      @search = params[:search]
  
      @products = Product.all
      @products = @products
        .where("title LIKE ? or body LIKE ?", "%#{@search}%", "%#{@search}%") if @search.present?
    #   @products = @products.page(params[:page]).per(5)
    end
  
    def show
      @product = Product.find(params[:id])
    end
  
    def new
      puts "This is how you print out something."
      @product = Product.new
    end
  
    def edit
      @product = Product.find(params[:id])
    end
  
    def create
      @product = Product.create(product_params)
  
      if @product.invalid?
        flash[:error] = @product.errors.full_messages
      end
  
      redirect_to action: :index
    end
  
    def update
      @product = Product.find(params[:id])
      @product.update(product_params)
      redirect_to action: :index
    end
  
    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to action: :index
    end
  
    private
  
    def product_params
      params.require(:product).permit(:name, :description, :stock)
    end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/test_articles_helper.rb
module TestArticlesHelper
end

app/views/articles/_form.slim
= form_with model: article do |f|
  div = f.text_field :title, placeholder: 'Title'
  div = f.text_area :body, placeholder: 'Write content here'
  div = f.submit 'Submit Article'

app/views/articles/edit.slim
h1 Edit article

div = link_to 'Back', articles_path
br
= render 'form', article: @article

app/views/articles/index.slim
.row
  .col-6
    h1 This is articles list
  .col-6
    .float-right
      span = current_admin.email
      span.ml-3 = "#{current_admin.firstname} #{current_admin.lastname}"
      span.ml-3 = link_to 'Logout', destroy_admin_session_path

.row
  .col
    = form_tag articles_path, method: :get do
      = text_field_tag 'search', @search, placeholder: 'Type something',
        class: 'form-control'

.row.mt-2
  .col
    table.table.table-bordered.table-striped.table-hover
      thead.thead-dark
        tr
          th ID
          th Title
          th Body
          th No. Comments
          th Created at
          th Updated at
          th Action
      tbody
        - @articles.each do |a|
          tr
            td = a.id
            td.font-weight-bold = a.title
            td = a.body
            td = a.comments.count
            td.font-weight-light = "#{time_ago_in_words(a.created_at)} Ago"
            td.font-weight-light = "#{time_ago_in_words(a.updated_at)} Ago"
            td
              span
                = link_to article_path(a) do
                  i.fas.fa-eye
              span.ml-3
                = link_to edit_article_path(a) do
                  i.fas.fa-pen
              span.ml-3
                = link_to article_path(a), method: :delete, data: { confirm: "Are you sure?" } do
                  i.fas.fa-trash

.row
  .col-6
    = paginate @articles
  .col-6
    .float-right
      = link_to new_article_path do
        = button_tag 'Add new Article', class: 'btn btn-primary'

app/views/articles/new.slim
h1 Add new article

div = link_to 'Back', articles_path
br
= render 'form', article: @article

app/views/articles/show.slim
h1 = @article.title
div = link_to 'Back', articles_path
hr
div = @article.body
hr
h2 Comments Section
div
  - @article.comments.each do |comment|
    div = "#{comment.author} Wrote : #{comment.text}"
hr
h2 Add new Comment Section
= form_with model: [@article, @article.comments.build] do |f|
  div = f.text_field :author, placeholder: 'Author'
  div = f.text_area :text, placeholder: 'Write text here'
  div = f.submit 'Submit Comment'

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.desc %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @category.desc %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css'%>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">
      <h1 style="color: red;">
        <%= flash[:error]&.join(',') %>
      </h1>
      <%= yield %>

      <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.slim.min.js' %>
      <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js' %>
      <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Blog</h1>
<%= link_to 'Home', root_path %>

app/views/pages/index.html.erb
<h1>Welcome to Blog (index.html.erb)</h1>
<%= link_to 'About', about_path %>

app/views/products/_form.html.erb
<%# / = form_with model: product do |f|
/   div = f.text_field :name, placeholder: 'Product name'
/   div = f.text_area :description, placeholder: 'Write description here'
/   div = f.text_field :stock, placeholder: 'number of stock'
/   div = f.select :category_id, options_for_select(@categories), :prompt => "Select one!"
/   div = f.submit 'Submit Product' %>

<%= form_with(model: product) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Category",) %>
  </div>
  <br>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>
<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.slim
.row
  .col-6
    h1 This is Products list
  .col-6
    .float-right
      / span = current_admin.email
      / span.ml-3 = "#{current_admin.firstname} #{current_admin.lastname}"
      span.ml-3 = link_to 'Logout', destroy_admin_session_path, method: :delete

.row
  .col
    = form_tag products_path, method: :get do
      = text_field_tag 'search', @search, placeholder: 'Type something',
        class: 'form-control'

.row.mt-2
  .col
    table.table.table-bordered.table-striped.table-hover
      thead.thead-dark
        tr
          th ID
          th Name
          th Description
          th Stock
          th Created at
          th Updated at
          th Action
      tbody
        - @products.each do |a|
          tr
            td = a.id
            td.font-weight-bold = a.name
            td = a.description
            td = a.stock
            td.font-weight-light = "#{time_ago_in_words(a.created_at)} Ago"
            td.font-weight-light = "#{time_ago_in_words(a.updated_at)} Ago"
            td
              span
                = link_to product_path(a) do
                  i.fas.fa-eye
              span.ml-3
                = link_to edit_product_path(a) do
                  i.fas.fa-pen
              span.ml-3
                = link_to product_path(a), method: :delete, data: { confirm: "Are you sure?" } do
                  i.fas.fa-trash

.row
  .col-6
    = paginate @products
  .col-6
    .float-right
      = link_to new_product_path do
        = button_tag 'Add new Product', class: 'btn btn-primary'

app/views/products/new.slim
h1 Add new article

div = link_to 'Back', products_path
br
= render 'form', product: @product

app/views/products/show.slim
h1 = @product.name
div = link_to 'Back', products_path
hr
div = @product.description
hr
div = @product.stock
hr
h2 Comments Section
/ div
/   - @article.comments.each do |comment|
/     div = "#{comment.author} Wrote : #{comment.text}"
/ hr
/ h2 Add new Comment Section
/ = form_with model: [@article, @article.comments.build] do |f|
/   div = f.text_field :author, placeholder: 'Author'
/   div = f.text_area :text, placeholder: 'Write text here'
/   div = f.submit 'Submit Comment'

app/views/test_articles/index.slim
h1 TestArticles

.row
  .col-6
    h1 This is Products list
  .col-6
    .float-right
      / span = current_admin.email
      / span.ml-3 = "#{current_admin.firstname} #{current_admin.lastname}"
      span.ml-3 = link_to 'Logout', destroy_admin_session_path, method: :delete

.row
  .col
    = form_tag products_path, method: :get do
      = text_field_tag 'search', @search, placeholder: 'Type something',
        class: 'form-control'

.row.mt-2
  .col
    table.table.table-bordered.table-striped.table-hover
      thead.thead-dark
        tr
          th ID
          th Name
          th Description
          th Stock
          th Created at
          th Updated at
          th Action
      tbody
        - @products.each do |a|
          tr
            td = a.id
            td.font-weight-bold = a.name
            td = a.description
            td = a.stock
            td.font-weight-light = "#{time_ago_in_words(a.created_at)} Ago"
            td.font-weight-light = "#{time_ago_in_words(a.updated_at)} Ago"
            td
              span
                = link_to product_path(a) do
                  i.fas.fa-eye
              span.ml-3
                = link_to edit_product_path(a) do
                  i.fas.fa-pen
              span.ml-3
                = link_to product_path(a), method: :delete, data: { confirm: "Are you sure?" } do
                  i.fas.fa-trash

.row
  / .col-6
  /   = paginate @products
  .col-6
    .float-right
      = link_to new_product_path do
        = button_tag 'Add new Product', class: 'btn btn-primary'

app/views/welcomes/index.slim
h1 This is header
h1 This is a second header
h2 This is a third header
h1
  ul
    - ['a', 'b', 'c', 'd'].each_with_index do |e,i|
      li = "#{i}. #{e}"

app/views/welcomes/index_backup.html.erb
<h1>
    <ul>
        <%= [1,2,3,4].map { |e| "<li> Item #{e} </li>" } %>
    </ul>
</h1>